In [ ]:
#Deep learning 

# This is dataset of customer churn analysis through ANN neural Network

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

In [37]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [38]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

Excluding 1st 3 rows as they are not relavent

In [5]:
X = dataset.iloc[:, 3:-1].values

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [39]:
X[:, 2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [40]:
X[:, 1]

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [9]:
### Encoding categorical data

In [41]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [42]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [45]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [16]:
### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential()

Adding layer to ANN 

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [21]:
## Part 3 - Training the ANN

In [24]:
from sklearn.model_selection import train_test_split
x_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Model Prediction

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [27]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [28]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6679 - accuracy: 0.5984: 0s - loss: 0.7490 - accura
Epoch 2/100
250/250 [==============================] - ETA: 0s - loss: 0.4717 - accuracy: 0.80 - 1s 2ms/step - loss: 0.4724 - accuracy: 0.8001
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4461 - accuracy: 0.8071
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4340 - accuracy: 0.8108
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4258 - accuracy: 0.8136
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4196 - accuracy: 0.8160
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4136 - accuracy: 0.8229
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4071 - accuracy: 0.8245
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4004 - accuracy: 0.8292: 0s - loss: 0.4015 - 

250/250 [==============================] - 1s 3ms/step - loss: 0.3369 - accuracy: 0.8621: 0s - loss: 0.3257 - ac
Epoch 74/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3370 - accuracy: 0.8622
Epoch 75/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3369 - accuracy: 0.8633: 0s - loss: 0.3387 - accuracy: 0.
Epoch 76/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3370 - accuracy: 0.8625
Epoch 77/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3362 - accuracy: 0.8616
Epoch 78/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3365 - accuracy: 0.8631
Epoch 79/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3363 - accuracy: 0.8616: 0s - loss: 0.3304 - ac
Epoch 80/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3360 - accuracy: 0.8614
Epoch 81/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3369 - accuracy: 0.8624: 0s - loss: 0

In [29]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1525   70]
 [ 206  199]]


0.862